In [34]:
import numpy as np
import pickle

In [35]:
ohe_sex = pickle.load(open("models/ohe_sex.pkl", 'rb'))
ohe_embarked = pickle.load(open("models/ohe_embarked.pkl", 'rb'))
clf = pickle.load(open("models/clf.pkl", 'rb'))

In [36]:
"""
##################
#   TEST INPUT   #
##################

PClass, gender, age, SibSp, Parch, Fare, Embarked
"""

test_input = np.array([2, 'male', 3.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [37]:
test_input

array([[2, 'male', 3.0, 0, 0, 10.5, 'S']], dtype=object)

In [38]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))

c:\Users\PMLS\OneDrive\Documents\MTTQ\CampusX\100DaysOfML\env\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [39]:
test_input_sex

array([[0., 1.]])

In [40]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [41]:
test_input_embarked

array([[0., 0., 1.]])

In [42]:
test_input_age = test_input[:, 2].reshape(1, 1)
test_input_age

array([[3.0]], dtype=object)

In [43]:
test_input_transformed = np.concatenate(
    (test_input[:, [0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked),
    axis=1
)

test_input_transformed

array([[2, 0, 0, 10.5, 3.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [44]:
clf.predict(test_input_transformed)

array([1])